##
## EPITECH PROJECT, 2025
## mydnetlib
## File description:
## Makefile
##


SRC 	=	$(shell find ../src -name "*.cpp")
TEST 	=	$(shell find ./ -name "*.cpp")
DFLAGS	=	-g -ggdb -g3

all:
	g++ $(SRC) $(TEST) $(DFLAGS) -I../include